# Generated by Django 4.2.11 on 2025-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='availability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='biology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='fishing_rate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='health_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='management',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='nutrition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='population',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='taste',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='texture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
