# Generated by Django 4.2.11 on 2025-06-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0002_fish_availability_fish_biology_fish_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='fish_images/'),
        ),
    ]
