# Generated by Django 4.2.11 on 2025-06-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0003_fish_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('method', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish_preparations/')),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('suitable_species', models.ManyToManyField(blank=True, to='fishapp.fish')),
            ],
        ),
        migrations.CreateModel(
            name='FishPod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish_pods/')),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_tips', models.TextField(blank=True, null=True)),
                ('suitable_species', models.ManyToManyField(blank=True, to='fishapp.fish')),
            ],
        ),
        migrations.CreateModel(
            name='FishingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fishing_methods/')),
                ('tools_required', models.TextField(blank=True, null=True)),
                ('is_traditional', models.BooleanField(default=False)),
                ('recommended_species', models.ManyToManyField(blank=True, to='fishapp.fish')),
            ],
        ),
    ]
